language: php

php:

  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=latest WP_MULTISITE=1
- WP_VERSION=4.4 WP_MULTISITE=0
- WP_VERSION=4.4 WP_MULTISITE=1

matrix:
  exclude:
    - php: hhvm
      env: WP_VERSION=3.9.2 WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=4.0 WP_MULTISITE=0

## Cache composer and external sources
cache: 
  directories: 
    - vendor 
    - $HOME/.composer/cache 

before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer self-update
- npm install -g npm
- bower update
- bower-installer

script:
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi
  
after_script:
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
  fi
